---
title: "Shiny Project"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(data.table)

raw_data_full <- fread("./Service_Requests_311.csv", stringsAsFactors = F, nrows=5000)
raw_data_full <- as.data.frame(raw_data_full)
raw_slice = fread('./Service_Requests_311.csv', select = c("Unique Key","Incident Zip","Incident Address", "Created Date", "Complaint Type",'Descriptor','Borough', 'Latitude','Longitude'), nrows=500000)
 names(raw_slice) <-  tolower(names(raw_slice))
 names(raw_slice) <- gsub(" ", '_', names(raw_slice))
# system.time({noise <- raw_slice %>% filter(., grepl('Noise.*', complaint_type))})



sum(desc_fast[12:nrow(desc_fast),2])/sum(desc_fast[1:10,2])
x123 <- desc_fast[13:nrow(desc_fast),]

table(is.na(raw_slice$complaint_type))
table(is.na(raw_slice$longitude))
table(raw_slice$incident_address[raw_slice$incident_address==""])


col_groups <- c('heating', 'noise','construction','plumbing', 'paint', 'unsanitary', 'parked_cars','street_lights_signals','tree','electric','vermin','street_sidewalk')
raw_slice <- raw_slice %>%
  filter(., !is.na(longitude)) %>%
  filter(., !incident_address=="") %>%
  mutate(.,complaint_type=gsub('(.*heat.*)', replacement=col_groups[1], x=complaint_type, ignore.case=TRUE)) %>% 
  mutate(.,complaint_type=gsub('(.*noise.*)', replacement=col_groups[2], x=complaint_type, ignore.case=TRUE))  %>%
  mutate(.,complaint_type=gsub('(.*construction.*)', replacement=col_groups[3], x=complaint_type, ignore.case=TRUE)) %>% 
  mutate(.,complaint_type=gsub('(.*plumbing*|.*water sys.*|.*leak.*)', replacement=col_groups[4], x=complaint_type, ignore.case=TRUE))%>%
  mutate(.,complaint_type=gsub('(.*paint.*)', replacement=col_groups[5], x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('(.*sani.*|.*dirty.*)', replacement=col_groups[6], x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('blocked driveway|Illegal Parking|Traffic$', replacement=col_groups[7], x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('.*(Street Sign).*|.*(Street Light).*|.*signal.*', replacement=col_groups[8], x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('((.*\\btree.*)|(branch))', replacement=col_groups[9], x=complaint_type, ignore.case=TRUE))%>%
    mutate(.,complaint_type=gsub('(.*electric.*)', replacement=col_groups[10], x=complaint_type, ignore.case=TRUE))%>%
  mutate(.,complaint_type=gsub('(.*rodent.*)|(.*nonconst.*)', replacement=col_groups[11], x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('(.*sidewalk.*)|(.*street\\b).*', replacement=col_groups[12], x=complaint_type, ignore.case=TRUE))%>% 
  filter(., complaint_type %in% col_groups)

####Most common hour for calls to be made
library(lubridate)
lubridate_test <- parse_date_time(raw_slice$created_date, 'mdY H!MS p' )
hour(lubridate_test)



Over_Hour<- raw_slice %>% group_by(.,created_date)  %>% summarize(.,count=n()) %>%
  mutate(day = weekdays(as.Date(created_date,format = "%m/%d/%Y")),year = year(as.Date(created_date,format = "%m/%d/%Y")), hour = hour(parse_date_time(created_date, 'mdY H!MS p' )))  %>% filter(., !substr(created_date,12,22)=='12:00:00 AM') %>% group_by(.,hour) %>% summarize(., sum=sum(count))                                                                          
library(googleVis)
Hourplot <- gvisLineChart(Over_Hour)
plot(Line)

Over_Day <- raw_slice %>% group_by(.,created_date)  %>% summarize(.,count=n()) %>%
  mutate(day = weekdays(as.Date(created_date,format = "%m/%d/%Y")),year = year(as.Date(created_date,format = "%m/%d/%Y")), hour = hour(parse_date_time(created_date, 'mdY H!MS p' ))) %>% group_by(.,day) %>% summarize(.,daysum=sum(count)) 

Over_Day$day <- factor(Over_Day$day,levels=c('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'))

View(Over_Day$day)

Dayplot <-  gvisLineChart(Over_Day[order(Over_Day$day),])
plot(Dayplot)

Over_HourDay <- raw_slice %>% group_by(.,created_date)  %>% summarize(.,count=n()) %>% filter(., !substr(created_date,12,22)=='12:00:00 AM') %>%
  mutate(day = weekdays(as.Date(created_date,format = "%m/%d/%Y")), hour = hour(parse_date_time(created_date, 'mdY H!MS p' )))  %>% mutate(., new_col=paste(hour,day,sep="")) %>% group_by(., new_col, day)  %>% summarize(.,weeksum=sum(count))# %>% arrange(., day, hour)

library(plotly)
x <- outer(c(0:23), c('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'), FUN = "paste")
c(x)
Over_HourDay$day <- factor(Over_HourDay$day,levels=c('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'))
Over_HourDay$new_col <- factor(Over_HourDay$new_col,levels=c(x),ordered = TRUE)
Hour_day_plot <- gvisLineChart(Over_HourDay[order(Over_HourDay$day),], xvar="day")
plot(Hour_day_plot)
p <- plot_ly(Over_HourDay, x = ~new_col, y = ~weeksum, type = 'scatter', mode = 'lines')
p
## Re-level the cars by mpg
mtcars3$car <-factor(mtcars2$car, levels=mtcars2[order(mtcars$mpg), "car"])
 

########

sort(table(raw_slice$complaint_type))
filter_test <- table(grep('(.*sidewalk.*)|(.*street\\b).*',x=desc_fast$complaint_type,ignore.case=TRUE,value = TRUE))
filter_test

desc_ <- raw_slice %>%   group_by(`complaint_type`) %>%
  summarise(count=n()) %>%
  #top_n(25,count) %>%
  arrange(.,desc(count))

desc_fast <- desc_ %>%
  mutate(.,complaint_type=gsub('(.*heat.*)', replacement='heating', x=complaint_type, ignore.case=TRUE)) %>% 
  mutate(.,complaint_type=gsub('(.*noise.*)', replacement='noise', x=complaint_type, ignore.case=TRUE))  %>%
  mutate(.,complaint_type=gsub('(.*construction.*)', replacement='construction', x=complaint_type, ignore.case=TRUE)) %>% 
  mutate(.,complaint_type=gsub('(.*plumbing*|.*water sys.*|.*leak.*)', replacement='plumbing', x=complaint_type, ignore.case=TRUE))%>%
  mutate(.,complaint_type=gsub('(.*paint.*)', replacement='paint', x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('(.*sani.*|.*dirty.*)', replacement='unsanitary', x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('blocked driveway|Illegal Parking|Traffic$', replacement='parked_cars', x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('.*(Street Sign).*|.*(Street Light).*|.*signal.*', replacement='street_lights_signals', x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('((.*\\btree.*)|(branch))', replacement='tree', x=complaint_type, ignore.case=TRUE))%>%
    mutate(.,complaint_type=gsub('(.*electric.*)', replacement='electric', x=complaint_type, ignore.case=TRUE))%>%
  mutate(.,complaint_type=gsub('(.*rodent.*)|(.*nonconst.*)', replacement='vermin', x=complaint_type, ignore.case=TRUE)) %>%
  mutate(.,complaint_type=gsub('(.*sidewalk.*)|(.*street\\b).*', replacement='street_sidewalk_condition', x=complaint_type, ignore.case=TRUE)) %>%
  group_by(., complaint_type) %>% 
  summarise(count = sum(count)) %>%  
  arrange(.,desc(count))

view1<- raw_slice %>% filter(., `complaint_type`=='paint')
table(view1$descriptor)

str(noise)

table(noise$descriptor)

library(maps)

colStates <- map("state", fill = TRUE, plot = FALSE,
                 region = c("florida", "louisiana", "mississippi", 
                            "alabama", "georgia", "tennesse"))
colStates
```

```{r}
top_addresses <- raw_slice %>% group_by(.,latitude, longitude, complaint_type, incident_address) %>% summarize(., count=n()) %>% arrange(.,desc(count))

library(shiny)
library(dplyr)
library(DT)
library(shinydashboard)
library(leaflet)
library(maps)
top_ad <- leaflet(head(top_addresses,20)) %>%
        addTiles() %>%
        addCircleMarkers(radius = top_addresses$count*.1)
top_ad

View(head(top_addresses,20))
```

